### ISSUE TITLE
Version 3.3.46 broke some things

### ISSUE THREAD

**Issue by Petosiris** [dolkensp/HangarXPLOR#45]
I installed the latest version, 3.3.46, in Chrome and now HangarXPLOR seems to think my hangar is empty. See attached screenshot.

![HangarXplor_3 3 6](https://user-images.githubusercontent.com/40414502/68987976-64c05480-0830-11ea-8b98-a3fcb66a6db5.jpg)

**Comment by dolkensp** [comment]
Thanks, CIG has made a few changes to the hangar. I’ll have to add detection for that but I’m flying to India today so it might be a day or two.

Thanks for the report

Peter Dolkens

**Comment by paulpv** [comment]
Odd.
Clear Cache? (The hard way or CTRL-SHIFT-R)

I cloned @dolkensp's master branch (not the official store extension) and it works fine for my two account hangars.
(non-trivial: 35 ships in one account, 29 in the other [includes an Idris, as you picture, albeit `P`/`K`])

A few ideas to help debug:
1) Can you open up the `Inspect` `Console` and see if there is any unusual debug output?
(I don't think this will help, since I think the code defaults to not logging; you would have to locally clone and turn on logging)
2) Same thing but looking at the Network requests instead.
3) Confirm w/ @dolkensp if this might help, but would you mind dumping your hangar to csv and sharing it here? It could be an unrelated break due to a second change RSI made. A csv usually contains little to no privacy info...but it would publicly tell viewers what you have, if you mind that or not.
4) Any way to revert to a previous version and confirm how much of that works for you on the latest site?
The reality is that the RSI site did change subtly, so the previous plugin was already broken w/ the new site, but it might shed some light on what is broken.
The new change was very tiny #44, so I can't think of what in that would cause what you are seeing.

First guess to me is to force the cache to reset, or uninstall and reinstall the plugin.

**Comment by paulpv** [comment]
Your screenshot shows you are hitting the code at:
https://github.com/dolkensp/HangarXPLOR/blob/develop/src/web_resources/HangarXPLOR.Render.js#L42

Do you have a filter set?

**Comment by Petosiris** [comment]
Actually, it works now here too. It may've helped to exit the browser and restart it, I don't know.

BTW, before this, I tried clearing the browser cache with Ctrl+F5 and there was no filter set. About posting my hangar here as a CSV - that wouldn't be my first choice, no, but @dolkensp already have my hangar from some time ago.

**Comment by dolkensp** [comment]
There was a NaN bug which I've pushed a fix for now.

Let me know if it occurs again.
